### ISSUE TITLE
Need to know when the Debian Security Update for gnutls28 (DLA 3070-1) vulnerability for local-volume provider will be fixed.

### ISSUE THREAD

**Issue by chaitutheprince** [replicatedhq/local-volume-provider#14]
Need to know when the Debian Security Update for gnutls28 (DLA 3070-1) vulnerability for local-volume provider will be fixed. Due data of the vulnerability shows as 09/15. we thought it will fix in kots 1.84 version. But it was not fixed. What is the ETA  for fixing this vulnerability.

**Comment by cbodonnell** [comment]
@chaitutheprince this CVE was fixed in local-volume-provider `v0.3.8` and was incorporated into kots `v1.85.0` (see release notes [here](https://docs.replicated.com/release-notes/rn-app-manager#improvements-1-85-0)).  I'm going to close out this issue as a result.

**Comment by chaitutheprince** [comment]
Thank you. Vulnerability cleared too.
